AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  The SAM Template for Deep Frying Tweets. Extra Crispy.

Resources:
  DeepFriedTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: deep-fried-table
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  DeepFriedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: deep-fried-bucket
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldImages
            Status: Enabled
            ExpirationInDays: 7

  ProcessMentionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter_py/
      Handler: handlers.process_mentions
      Runtime: python3.8
      Timeout: 10
      Events:
        CheckMentionsScheduledEvent:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: rate(1 minute)
      Environment:
        Variables:
          TABLE_NAME: !Ref DeepFriedTable
          SCREENSHOT_TWEET_FUNCTION: !Ref ScreenshotTweetFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeepFriedTable
        - LambdaInvokePolicy:
            FunctionName: !Ref ScreenshotTweetFunction

  ScreenshotTweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: screenshot_tweet/
      Handler: handler.handler
      Runtime: nodejs14.x
      Timeout: 20
      MemorySize: 512
      Environment:
        Variables:
          BUCKET_NAME: !Ref DeepFriedBucket
          DEEP_FRY_FUNCTION: !Ref DeepFryFunction
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DeepFriedBucket
        - LambdaInvokePolicy:
            FunctionName: !Ref DeepFryFunction

  DeepFryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deep_fry/
      Handler: handler.handler
      Runtime: nodejs12.x
      Timeout: 20
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DeepFriedBucket
        - S3WritePolicy:
            BucketName: !Ref DeepFriedBucket
        - LambdaInvokePolicy:
            FunctionName: !Ref ReplyFunction
      Environment:
        Variables:
          BUCKET_NAME: !Ref DeepFriedBucket
          REPLY_FUNCTION: !Ref ReplyFunction

  ReplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter_py/
      Handler: handlers.reply
      Runtime: python3.8
      Timeout: 20
      Environment:
        Variables:
          BUCKET_NAME: !Ref DeepFriedBucket
          TABLE_NAME: !Ref DeepFriedTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DeepFriedBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DeepFriedTable

Outputs:
  DeepFriedTable:
    Description: Deep Fried Table ID
    Value: !Ref DeepFriedTable
  DeepFriedBucket:
    Description: Deep Fried Bucket Name
    Value: !Ref DeepFriedBucket
  ScreenshotTweetFunction:
    Description: Name of the screenshot tweet function
    Value: !Ref ScreenshotTweetFunction
  DeepFryFunction:
    Description: Name of the deep fry function
    Value: !Ref DeepFryFunction
  ReplyFunction:
    Description: Name of the reply function
    Value: !Ref ReplyFunction
