AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  The SAM Template for Deep Frying Tweets. Extra Crispy.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: !Ref DeepFriedTable

Resources:
  DeepFriedTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: deep-fried-table
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ProcessMentionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter_py/
      Handler: app.process_mentions
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeepFriedTable
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref ScreenshotTweetFunction

  DeepFriedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: deep-fried-bucket

  ScreenshotTweetLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: The dependencies for the Chromium screenshot-taker
      ContentUri: ./
      RetentionPolicy: Delete

  ScreenshotTweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./screenshot_tweet/app.handler
      Runtime: nodejs14.x
      Timeout: 20
      MemorySize: 1024
      Layers:
        - !Ref ScreenshotTweetLayer
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DeepFriedBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref DeepFriedBucket

Outputs:
  DeepFriedTable:
    Description: Deep Fried Table ID
    Value: !Ref DeepFriedTable
  DeepFriedBucket:
    Description: Deep Fried Bucket Name
    Value: !Ref DeepFriedBucket
