AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  The SAM Template for Deep Frying Tweets. Extra Crispy.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3

Resources:
  DeepFriedTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: deep-fried-table
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ProcessMentionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter_py/
      Handler: app.process_mentions
      Runtime: python3.8
      Environment:
        Variables:
          DEEP_FRIED_TABLE: !Ref DeepFriedTable

Outputs:
  DeepFriedTable:
    Description: Deep Fried Table ID
    Value: !Ref DeepFriedTable
